const INCREASE_ADULT_COUNT = "GUEST/ADULT/INCREASE_COUNT";
const DECREASE_ADULT_COUNT = "GUEST/ADULT/DECREASE_COUNT";
const INCREASE_CHILDREN_COUNT = "GUEST/CHILDREN/INCREASE_COUNT";
const DECREASE_CHILDREN_COUNT = "GUEST/CHILDREN/DECREASE_COUNT";
const INCREASE_INFANTS_COUNT = "GUEST/INFANTS/INCREASE_COUNT";
const DECREASE_INFANTS_COUNT = "GUEST/INFANTS/DECREASE_COUNT";

export {
  INCREASE_ADULT_COUNT,
  DECREASE_ADULT_COUNT,
  INCREASE_CHILDREN_COUNT,
  DECREASE_CHILDREN_COUNT,
  INCREASE_INFANTS_COUNT,
  DECREASE_INFANTS_COUNT
};