spring:
  profiles:
    active: dev
  flyway:
    clean-on-validation-error: true
management:
  endpoints:
    web:
      exposure:
        exclude: env,beans
        include: "*"
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/airbnb?characterEncoding=UTF-8
    username: airbnb
    password: airbnb
  flyway:
    user: airbnb
    password: airbnb
    url: jdbc:mysql://localhost:3306/airbnb?characterEncoding=UTF-8

logging:
  level:
    web: debug
    sql: debug
    kr.codesquad.airbnb11: debug

host: localhost:8080
github:
  client-id: 9875df2fa499cdb9ff25
  client-secret: d1dff8a224738636f3fb0e6a3781b5ee8c17f494

---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://accommodation-db.cr55utyiscde.ap-northeast-2.rds.amazonaws.com/airbnb?characterEncoding=UTF-8
    username: airbnb11
    password: airbnb11
  flyway:
    url: jdbc:mysql://accommodation-db.cr55utyiscde.ap-northeast-2.rds.amazonaws.com/airbnb?characterEncoding=UTF-8
    user: airbnb11
    password: airbnb11

logging:
  level:
    web: debug
    sql: debug
    kr.codesquad.airbnb11: debug

host: 13.124.223.191/api
github:
  client-id: ee75619e5811bb328936
  client-secret: a13148ae7b76f7ce892d6d315da636b9b19a2faf

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://airbnb11.ckvak2aogy3v.us-east-1.rds.amazonaws.com/airbnb?characterEncoding=UTF-8
    username: airbnb11
    password: airbnb11
  flyway:
    url: jdbc:mysql://airbnb11.ckvak2aogy3v.us-east-1.rds.amazonaws.com/airbnb?characterEncoding=UTF-8
    user: airbnb11
    password: airbnb11

logging:
  level:
    web: debug
    sql: debug
    kr.codesquad.airbnb11: debug

host: 3.232.101.173/api
github:
  client-id: 079d5502cd95167fd24b
  client-secret: d79455358c12197814137009b0ad5c7fb733ee2a

