# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle & Deploy SpringBoot to Amazon EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BE

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws deploy push --application-name airbnb-11 --description "This is a revision for the application" --s3-location s3://accommodation-s3/server/Build.zip --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name airbnb-11 --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name master --s3-location bucket=accommodation-s3,bundleType=zip,key=server/Build.zip
