# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: FE

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run npm ci
      run: npm ci

    - name: Run npm run build
      run: npm run build --if-present

    - name: Run npm test
      run: npm test
