# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: FE

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run npm ci
      run: npm ci

    - name: Run npm run build
      run: npm run build --if-present
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws deploy push --application-name airbnb-11-fe --description "This is a revision for the application" --s3-location s3://accommodation-s3/server/FE-Build.zip --source .

    - name: Code Deploy
      run: aws deploy create-deployment --application-name airbnb-11-fe --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name fe-master --s3-location bucket=accommodation-s3,bundleType=zip,key=server/FE-Build.zip

